/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PhaseId = IDL.Nat;
export const ExerciseId = IDL.Nat;
export const DurationUnit = IDL.Variant({
  'minutes' : IDL.Null,
  'seconds' : IDL.Null,
});
export const Duration = IDL.Record({
  'value' : IDL.Nat,
  'unit' : DurationUnit,
});
export const Exercise = IDL.Record({
  'weight' : IDL.Nat,
  'duration' : Duration,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'notes' : IDL.Text,
});
export const DayOfWeek = IDL.Variant({
  'tuesday' : IDL.Null,
  'wednesday' : IDL.Null,
  'saturday' : IDL.Null,
  'thursday' : IDL.Null,
  'sunday' : IDL.Null,
  'friday' : IDL.Null,
  'monday' : IDL.Null,
});
export const Time = IDL.Int;
export const WorkoutSession = IDL.Record({
  'day' : DayOfWeek,
  'weight' : IDL.Nat,
  'duration' : IDL.Nat,
  'date' : Time,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'notes' : IDL.Text,
  'exerciseName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkoutTemplateView = IDL.Record({
  'days' : IDL.Vec(DayOfWeek),
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
});
export const Phase = IDL.Record({
  'id' : PhaseId,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
});
export const UserWorkoutTemplateView = IDL.Record({
  'id' : IDL.Nat,
  'template' : WorkoutTemplateView,
});
export const WeightUnit = IDL.Variant({ 'kg' : IDL.Null, 'lbs' : IDL.Null });
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'weightUnit' : WeightUnit,
});
export const LogEntryId = IDL.Nat;
export const PhaseExerciseLog = IDL.Record({
  'id' : LogEntryId,
  'weight' : IDL.Nat,
  'exerciseId' : ExerciseId,
  'date' : Time,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
});
export const PhaseExercise = IDL.Record({
  'id' : ExerciseId,
  'name' : IDL.Text,
  'phaseId' : PhaseId,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addExerciseToPhase' : IDL.Func([PhaseId, IDL.Text], [ExerciseId], []),
  'addExerciseToTemplate' : IDL.Func([IDL.Nat, Exercise], [IDL.Bool], []),
  'addWorkout' : IDL.Func([WorkoutSession], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPhase' : IDL.Func([IDL.Text], [PhaseId], []),
  'createWorkoutTemplate' : IDL.Func([WorkoutTemplateView], [IDL.Bool], []),
  'deletePhase' : IDL.Func([PhaseId], [IDL.Bool], []),
  'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], []),
  'getAllPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
  'getAllWorkoutTemplates' : IDL.Func(
      [],
      [IDL.Vec(UserWorkoutTemplateView)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExerciseLogs' : IDL.Func(
      [ExerciseId],
      [IDL.Vec(PhaseExerciseLog)],
      ['query'],
    ),
  'getExercisesForPhase' : IDL.Func(
      [PhaseId],
      [IDL.Vec(PhaseExercise)],
      ['query'],
    ),
  'getOwnWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserWorkoutHistory' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'getWorkoutSessionsByDateRange' : IDL.Func(
      [Time, Time],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'getWorkoutSessionsByDay' : IDL.Func(
      [DayOfWeek],
      [IDL.Vec(WorkoutSession)],
      ['query'],
    ),
  'getWorkoutTemplatesByDay' : IDL.Func(
      [DayOfWeek],
      [IDL.Vec(UserWorkoutTemplateView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logExercise' : IDL.Func(
      [ExerciseId, IDL.Nat, IDL.Nat, IDL.Nat],
      [LogEntryId],
      [],
    ),
  'removeExercise' : IDL.Func([ExerciseId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateTemplateName' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Opt(IDL.Text)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PhaseId = IDL.Nat;
  const ExerciseId = IDL.Nat;
  const DurationUnit = IDL.Variant({
    'minutes' : IDL.Null,
    'seconds' : IDL.Null,
  });
  const Duration = IDL.Record({ 'value' : IDL.Nat, 'unit' : DurationUnit });
  const Exercise = IDL.Record({
    'weight' : IDL.Nat,
    'duration' : Duration,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const DayOfWeek = IDL.Variant({
    'tuesday' : IDL.Null,
    'wednesday' : IDL.Null,
    'saturday' : IDL.Null,
    'thursday' : IDL.Null,
    'sunday' : IDL.Null,
    'friday' : IDL.Null,
    'monday' : IDL.Null,
  });
  const Time = IDL.Int;
  const WorkoutSession = IDL.Record({
    'day' : DayOfWeek,
    'weight' : IDL.Nat,
    'duration' : IDL.Nat,
    'date' : Time,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'notes' : IDL.Text,
    'exerciseName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkoutTemplateView = IDL.Record({
    'days' : IDL.Vec(DayOfWeek),
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
  });
  const Phase = IDL.Record({
    'id' : PhaseId,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
  });
  const UserWorkoutTemplateView = IDL.Record({
    'id' : IDL.Nat,
    'template' : WorkoutTemplateView,
  });
  const WeightUnit = IDL.Variant({ 'kg' : IDL.Null, 'lbs' : IDL.Null });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'weightUnit' : WeightUnit,
  });
  const LogEntryId = IDL.Nat;
  const PhaseExerciseLog = IDL.Record({
    'id' : LogEntryId,
    'weight' : IDL.Nat,
    'exerciseId' : ExerciseId,
    'date' : Time,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
  });
  const PhaseExercise = IDL.Record({
    'id' : ExerciseId,
    'name' : IDL.Text,
    'phaseId' : PhaseId,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addExerciseToPhase' : IDL.Func([PhaseId, IDL.Text], [ExerciseId], []),
    'addExerciseToTemplate' : IDL.Func([IDL.Nat, Exercise], [IDL.Bool], []),
    'addWorkout' : IDL.Func([WorkoutSession], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPhase' : IDL.Func([IDL.Text], [PhaseId], []),
    'createWorkoutTemplate' : IDL.Func([WorkoutTemplateView], [IDL.Bool], []),
    'deletePhase' : IDL.Func([PhaseId], [IDL.Bool], []),
    'deleteTemplate' : IDL.Func([IDL.Nat], [IDL.Opt(IDL.Text)], []),
    'getAllPhases' : IDL.Func([], [IDL.Vec(Phase)], ['query']),
    'getAllWorkoutTemplates' : IDL.Func(
        [],
        [IDL.Vec(UserWorkoutTemplateView)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExerciseLogs' : IDL.Func(
        [ExerciseId],
        [IDL.Vec(PhaseExerciseLog)],
        ['query'],
      ),
    'getExercisesForPhase' : IDL.Func(
        [PhaseId],
        [IDL.Vec(PhaseExercise)],
        ['query'],
      ),
    'getOwnWorkoutHistory' : IDL.Func([], [IDL.Vec(WorkoutSession)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserWorkoutHistory' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getWorkoutSessionsByDateRange' : IDL.Func(
        [Time, Time],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getWorkoutSessionsByDay' : IDL.Func(
        [DayOfWeek],
        [IDL.Vec(WorkoutSession)],
        ['query'],
      ),
    'getWorkoutTemplatesByDay' : IDL.Func(
        [DayOfWeek],
        [IDL.Vec(UserWorkoutTemplateView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logExercise' : IDL.Func(
        [ExerciseId, IDL.Nat, IDL.Nat, IDL.Nat],
        [LogEntryId],
        [],
      ),
    'removeExercise' : IDL.Func([ExerciseId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateTemplateName' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Opt(IDL.Text)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };