/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    weight: bigint;
    duration: bigint;
    name: string;
    reps: bigint;
    sets: bigint;
    notes: string;
}
export interface PhaseExerciseLog {
    id: LogEntryId;
    weight: bigint;
    exerciseId: ExerciseId;
    date: Time;
    reps: bigint;
    sets: bigint;
}
export type Time = bigint;
export interface WorkoutSession {
    day: DayOfWeek;
    weight: bigint;
    duration: bigint;
    date: Time;
    reps: bigint;
    sets: bigint;
    notes: string;
    exerciseName: string;
}
export type PhaseId = bigint;
export interface UserWorkoutTemplateView {
    id: bigint;
    template: WorkoutTemplateView;
}
export type LogEntryId = bigint;
export interface Phase {
    id: PhaseId;
    owner: Principal;
    name: string;
}
export type ExerciseId = bigint;
export interface WorkoutTemplateView {
    days: Array<DayOfWeek>;
    name: string;
    exercises: Array<Exercise>;
}
export interface UserProfile {
    name: string;
    weightUnit: WeightUnit;
}
export interface PhaseExercise {
    id: ExerciseId;
    name: string;
    phaseId: PhaseId;
}
export enum DayOfWeek {
    tuesday = "tuesday",
    wednesday = "wednesday",
    saturday = "saturday",
    thursday = "thursday",
    sunday = "sunday",
    friday = "friday",
    monday = "monday"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WeightUnit {
    kg = "kg",
    lbs = "lbs"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addExerciseToPhase(phaseId: PhaseId, name: string): Promise<ExerciseId>;
    addExerciseToTemplate(templateId: bigint, exercise: Exercise): Promise<boolean>;
    addWorkout(session: WorkoutSession): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPhase(name: string): Promise<PhaseId>;
    createWorkoutTemplate(template: WorkoutTemplateView): Promise<boolean>;
    deletePhase(phaseId: PhaseId): Promise<boolean>;
    getAllPhases(): Promise<Array<Phase>>;
    getAllWorkoutTemplates(): Promise<Array<UserWorkoutTemplateView>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExerciseLogs(exerciseId: ExerciseId): Promise<Array<PhaseExerciseLog>>;
    getExercisesForPhase(phaseId: PhaseId): Promise<Array<PhaseExercise>>;
    getOwnWorkoutHistory(): Promise<Array<WorkoutSession>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserWorkoutHistory(user: Principal): Promise<Array<WorkoutSession>>;
    getWorkoutSessionsByDateRange(startDate: Time, endDate: Time): Promise<Array<WorkoutSession>>;
    getWorkoutSessionsByDay(day: DayOfWeek): Promise<Array<WorkoutSession>>;
    getWorkoutTemplatesByDay(day: DayOfWeek): Promise<Array<UserWorkoutTemplateView>>;
    isCallerAdmin(): Promise<boolean>;
    logExercise(exerciseId: ExerciseId, sets: bigint, reps: bigint, weight: bigint): Promise<LogEntryId>;
    removeExercise(exerciseId: ExerciseId): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { DayOfWeek as _DayOfWeek, Exercise as _Exercise, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserWorkoutTemplateView as _UserWorkoutTemplateView, WeightUnit as _WeightUnit, WorkoutSession as _WorkoutSession, WorkoutTemplateView as _WorkoutTemplateView } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addExerciseToPhase(arg0: PhaseId, arg1: string): Promise<ExerciseId> {
        if (this.processError) {
            try {
                const result = await this.actor.addExerciseToPhase(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExerciseToPhase(arg0, arg1);
            return result;
        }
    }
    async addExerciseToTemplate(arg0: bigint, arg1: Exercise): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addExerciseToTemplate(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExerciseToTemplate(arg0, arg1);
            return result;
        }
    }
    async addWorkout(arg0: WorkoutSession): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWorkout(to_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWorkout(to_candid_WorkoutSession_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPhase(arg0: string): Promise<PhaseId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPhase(arg0);
            return result;
        }
    }
    async createWorkoutTemplate(arg0: WorkoutTemplateView): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkoutTemplate(to_candid_WorkoutTemplateView_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkoutTemplate(to_candid_WorkoutTemplateView_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deletePhase(arg0: PhaseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePhase(arg0);
            return result;
        }
    }
    async getAllPhases(): Promise<Array<Phase>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPhases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPhases();
            return result;
        }
    }
    async getAllWorkoutTemplates(): Promise<Array<UserWorkoutTemplateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkoutTemplates();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkoutTemplates();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExerciseLogs(arg0: ExerciseId): Promise<Array<PhaseExerciseLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExerciseLogs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExerciseLogs(arg0);
            return result;
        }
    }
    async getExercisesForPhase(arg0: PhaseId): Promise<Array<PhaseExercise>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercisesForPhase(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercisesForPhase(arg0);
            return result;
        }
    }
    async getOwnWorkoutHistory(): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnWorkoutHistory();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnWorkoutHistory();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWorkoutHistory(arg0: Principal): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWorkoutHistory(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWorkoutHistory(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutSessionsByDateRange(arg0: Time, arg1: Time): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSessionsByDateRange(arg0, arg1);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSessionsByDateRange(arg0, arg1);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutSessionsByDay(arg0: DayOfWeek): Promise<Array<WorkoutSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutSessionsByDay(to_candid_DayOfWeek_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutSessionsByDay(to_candid_DayOfWeek_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkoutTemplatesByDay(arg0: DayOfWeek): Promise<Array<UserWorkoutTemplateView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkoutTemplatesByDay(to_candid_DayOfWeek_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkoutTemplatesByDay(to_candid_DayOfWeek_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logExercise(arg0: ExerciseId, arg1: bigint, arg2: bigint, arg3: bigint): Promise<LogEntryId> {
        if (this.processError) {
            try {
                const result = await this.actor.logExercise(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logExercise(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async removeExercise(arg0: ExerciseId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeExercise(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeExercise(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_DayOfWeek_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DayOfWeek): DayOfWeek {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserWorkoutTemplateView_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserWorkoutTemplateView): UserWorkoutTemplateView {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_WeightUnit_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeightUnit): WeightUnit {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutSession_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutSession): WorkoutSession {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_WorkoutTemplateView_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkoutTemplateView): WorkoutTemplateView {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    template: _WorkoutTemplateView;
}): {
    id: bigint;
    template: WorkoutTemplateView;
} {
    return {
        id: value.id,
        template: from_candid_WorkoutTemplateView_n13(_uploadFile, _downloadFile, value.template)
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    days: Array<_DayOfWeek>;
    name: string;
    exercises: Array<_Exercise>;
}): {
    days: Array<DayOfWeek>;
    name: string;
    exercises: Array<Exercise>;
} {
    return {
        days: from_candid_vec_n15(_uploadFile, _downloadFile, value.days),
        name: value.name,
        exercises: value.exercises
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    weightUnit: _WeightUnit;
}): {
    name: string;
    weightUnit: WeightUnit;
} {
    return {
        name: value.name,
        weightUnit: from_candid_WeightUnit_n21(_uploadFile, _downloadFile, value.weightUnit)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: _DayOfWeek;
    weight: bigint;
    duration: bigint;
    date: _Time;
    reps: bigint;
    sets: bigint;
    notes: string;
    exerciseName: string;
}): {
    day: DayOfWeek;
    weight: bigint;
    duration: bigint;
    date: Time;
    reps: bigint;
    sets: bigint;
    notes: string;
    exerciseName: string;
} {
    return {
        day: from_candid_DayOfWeek_n16(_uploadFile, _downloadFile, value.day),
        weight: value.weight,
        duration: value.duration,
        date: value.date,
        reps: value.reps,
        sets: value.sets,
        notes: value.notes,
        exerciseName: value.exerciseName
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
}): DayOfWeek {
    return "tuesday" in value ? DayOfWeek.tuesday : "wednesday" in value ? DayOfWeek.wednesday : "saturday" in value ? DayOfWeek.saturday : "thursday" in value ? DayOfWeek.thursday : "sunday" in value ? DayOfWeek.sunday : "friday" in value ? DayOfWeek.friday : "monday" in value ? DayOfWeek.monday : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kg: null;
} | {
    lbs: null;
}): WeightUnit {
    return "kg" in value ? WeightUnit.kg : "lbs" in value ? WeightUnit.lbs : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserWorkoutTemplateView>): Array<UserWorkoutTemplateView> {
    return value.map((x)=>from_candid_UserWorkoutTemplateView_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DayOfWeek>): Array<DayOfWeek> {
    return value.map((x)=>from_candid_DayOfWeek_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkoutSession>): Array<WorkoutSession> {
    return value.map((x)=>from_candid_WorkoutSession_n26(_uploadFile, _downloadFile, x));
}
function to_candid_DayOfWeek_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): _DayOfWeek {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_WeightUnit_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeightUnit): _WeightUnit {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutSession_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutSession): _WorkoutSession {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WorkoutTemplateView_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkoutTemplateView): _WorkoutTemplateView {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    day: DayOfWeek;
    weight: bigint;
    duration: bigint;
    date: Time;
    reps: bigint;
    sets: bigint;
    notes: string;
    exerciseName: string;
}): {
    day: _DayOfWeek;
    weight: bigint;
    duration: bigint;
    date: _Time;
    reps: bigint;
    sets: bigint;
    notes: string;
    exerciseName: string;
} {
    return {
        day: to_candid_DayOfWeek_n3(_uploadFile, _downloadFile, value.day),
        weight: value.weight,
        duration: value.duration,
        date: value.date,
        reps: value.reps,
        sets: value.sets,
        notes: value.notes,
        exerciseName: value.exerciseName
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    weightUnit: WeightUnit;
}): {
    name: string;
    weightUnit: _WeightUnit;
} {
    return {
        name: value.name,
        weightUnit: to_candid_WeightUnit_n30(_uploadFile, _downloadFile, value.weightUnit)
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    days: Array<DayOfWeek>;
    name: string;
    exercises: Array<Exercise>;
}): {
    days: Array<_DayOfWeek>;
    name: string;
    exercises: Array<_Exercise>;
} {
    return {
        days: to_candid_vec_n9(_uploadFile, _downloadFile, value.days),
        name: value.name,
        exercises: value.exercises
    };
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeightUnit): {
    kg: null;
} | {
    lbs: null;
} {
    return value == WeightUnit.kg ? {
        kg: null
    } : value == WeightUnit.lbs ? {
        lbs: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DayOfWeek): {
    tuesday: null;
} | {
    wednesday: null;
} | {
    saturday: null;
} | {
    thursday: null;
} | {
    sunday: null;
} | {
    friday: null;
} | {
    monday: null;
} {
    return value == DayOfWeek.tuesday ? {
        tuesday: null
    } : value == DayOfWeek.wednesday ? {
        wednesday: null
    } : value == DayOfWeek.saturday ? {
        saturday: null
    } : value == DayOfWeek.thursday ? {
        thursday: null
    } : value == DayOfWeek.sunday ? {
        sunday: null
    } : value == DayOfWeek.friday ? {
        friday: null
    } : value == DayOfWeek.monday ? {
        monday: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<DayOfWeek>): Array<_DayOfWeek> {
    return value.map((x)=>to_candid_DayOfWeek_n3(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
