/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DayOfWeek = { 'tuesday' : null } |
  { 'wednesday' : null } |
  { 'saturday' : null } |
  { 'thursday' : null } |
  { 'sunday' : null } |
  { 'friday' : null } |
  { 'monday' : null };
export interface Exercise {
  'weight' : bigint,
  'duration' : bigint,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'notes' : string,
}
export type ExerciseId = bigint;
export type LogEntryId = bigint;
export interface Phase { 'id' : PhaseId, 'owner' : Principal, 'name' : string }
export interface PhaseExercise {
  'id' : ExerciseId,
  'name' : string,
  'phaseId' : PhaseId,
}
export interface PhaseExerciseLog {
  'id' : LogEntryId,
  'weight' : bigint,
  'exerciseId' : ExerciseId,
  'date' : Time,
  'reps' : bigint,
  'sets' : bigint,
}
export type PhaseId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string, 'weightUnit' : WeightUnit }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWorkoutTemplateView {
  'id' : bigint,
  'template' : WorkoutTemplateView,
}
export type WeightUnit = { 'kg' : null } |
  { 'lbs' : null };
export interface WorkoutSession {
  'day' : DayOfWeek,
  'weight' : bigint,
  'duration' : bigint,
  'date' : Time,
  'reps' : bigint,
  'sets' : bigint,
  'notes' : string,
  'exerciseName' : string,
}
export interface WorkoutTemplateView {
  'days' : Array<DayOfWeek>,
  'name' : string,
  'exercises' : Array<Exercise>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addExerciseToPhase' : ActorMethod<[PhaseId, string], ExerciseId>,
  'addExerciseToTemplate' : ActorMethod<[bigint, Exercise], boolean>,
  'addWorkout' : ActorMethod<[WorkoutSession], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPhase' : ActorMethod<[string], PhaseId>,
  'createWorkoutTemplate' : ActorMethod<[WorkoutTemplateView], boolean>,
  'deletePhase' : ActorMethod<[PhaseId], boolean>,
  'getAllPhases' : ActorMethod<[], Array<Phase>>,
  'getAllWorkoutTemplates' : ActorMethod<[], Array<UserWorkoutTemplateView>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExerciseLogs' : ActorMethod<[ExerciseId], Array<PhaseExerciseLog>>,
  'getExercisesForPhase' : ActorMethod<[PhaseId], Array<PhaseExercise>>,
  'getOwnWorkoutHistory' : ActorMethod<[], Array<WorkoutSession>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserWorkoutHistory' : ActorMethod<[Principal], Array<WorkoutSession>>,
  'getWorkoutSessionsByDateRange' : ActorMethod<
    [Time, Time],
    Array<WorkoutSession>
  >,
  'getWorkoutSessionsByDay' : ActorMethod<[DayOfWeek], Array<WorkoutSession>>,
  'getWorkoutTemplatesByDay' : ActorMethod<
    [DayOfWeek],
    Array<UserWorkoutTemplateView>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logExercise' : ActorMethod<[ExerciseId, bigint, bigint, bigint], LogEntryId>,
  'removeExercise' : ActorMethod<[ExerciseId], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];